### ISSUE TITLE
Remove Email

### ISSUE THREAD

**Issue by gtalarico** [szabgab/pydigger.com#1]
Hi! 
Somehow my personal email is showing up here:
http://pydigger.com/pypi/foldify
Would it be possible for you to remove it?
thanks!

![image](https://cloud.githubusercontent.com/assets/9513968/19731415/495067ce-9b6b-11e6-8cd4-7b2b95bb54a7.png)

**Comment by szabgab** [comment]
Thanks or reporting.

The data is retrieved from PyPI and the packages themselves so they were already public.
Nevertheless I'll look into it and will let you know where was it taken from and how to eliminate it.

**Comment by gtalarico** [comment]
Thanks. I think I accidently posted to pypi, but have already removed it. 
Thanks you for your help.

**Comment by gtalarico** [comment]
hi @szabgab 
My email is still showing in this page.
The package has been removed from Pypi
Could you kindly delete the page?
http://pydigger.com/pypi/foldify

**Comment by szabgab** [comment]
Sorry for the delay. I've removed it now.

**Comment by gtalarico** [comment]
Thank you, appreciated it

**Comment by szabgab** [comment]
BTW Why have you removed it from PyPI ?

**Comment by gtalarico** [comment]
It was my first pkg, I was testing some things out.
I will put it up again soon
