### ISSUE TITLE
Remove ipor-fusion-sdk package from pydigger

### ISSUE THREAD

**Issue by rav-ipor** [szabgab/pydigger.com#154]
Hello!

Please remove package with old name `ipor-fusion-sdk` from `pydigger`:
https://pydigger.com/pypi/ipor-fusion-sdk
The new one is just `ipor-fusion` here:
https://pydigger.com/pypi/ipor-fusion
It is also removed from `pypi`.

Regards,
rav

**Comment by szabgab** [comment]
done. Thanks for reporting.
