### ISSUE TITLE
https://pydigger.com/ seems down?

### ISSUE THREAD

**Issue by pombredanne** [szabgab/pydigger.com#77]
I have a bad hair day!
After https://github.com/pyinstaller/pyinstaller/issues/6490
 now https://pydigger.com/ seems down too

**Comment by szabgab** [comment]
I restarted it, but how did you make the connection?

**Comment by pombredanne** [comment]
> I restarted it, but how did you make the connection?

Either I am a freaky mind reader :exploding_head:  or more simply here is my journey:

- it all started with several users reporting installation issues for https://github.com/nexB/scancode-toolkit all related to specxific support of combos of Python versions, OS and architecture. Some of our deps contain native code beyond pure Python and this means we have more dependencies on the underlying platform than a pure Python application.  
- actually, way too many issues with linux/windows/macOS  installations problems per https://github.com/nexB/scancode-toolkit/issues?q=is%3Aopen+is%3Aissue+label%3A"installation+and+packaging"
- this made we wanting to revisit this long pending issue https://github.com/nexB/scancode-toolkit/issues/1703
- ... and thinking about how to bundle a Python interpreter and support only one Python version for the app bundles we release at https://github.com/nexB/scancode-toolkit/releases to have fewer moving parts. 
- I went to http://www.pyinstaller.org/ that I had been trackoing for a while 
- http://www.pyinstaller.org/  was down. 
- I went to https://github.com/pyinstaller/pyinstaller/ 
- and found https://github.com/pyinstaller/pyinstaller/issues/6490 
- and saw your comment at  https://github.com/pyinstaller/pyinstaller/issues/6490#issuecomment-1042629203 
- then clicked on your profile link to https://github.com/szabgab 
- and from then to https://pydigger.com/ which is the second link on your profile :) 
- ... which was down... 
- which brought me here. 

side note on I like very much what you are doing here.... kwalitee for Python :bow:

**Comment by szabgab** [comment]
It seems that these days Pydigger is usually up.

And BTW thanks for the detailed route description :smile:
