### ISSUE TITLE
Remove outdated pages

### ISSUE THREAD

**Issue by seebye** [szabgab/pydigger.com#79]
Hello,  

I wanted to ask if you could remove the pages about my abandoned projects (all packages are removed from pypi)?
Many thanks in advance.

https://pydigger.com/pypi/moving-chameleon
https://pydigger.com/pypi/ueberzug
https://pydigger.com/pypi/urwid-ueberzogen
https://pydigger.com/author/Nico%20Baeurer

**Comment by szabgab** [comment]
The good new is that they are gone now.
The bad new is that by mistake I nuked the whole database.

Well, well. :smile:
